#!/bin/sh

# Original script from https://github.com/aharris88/dotfiles
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles


dir=~/dotfiles                    # dotfiles directory
backupdir=~/dotfiles_backup          # old dotfiles backup directory

# Files/dirs to symlink to ~
homefiles="gitconfig gitignore_global agignore antigen vim vimrc basicvimrc nvim nvimrc tmux tmux.conf zshrc"
configfiles="htoprc"

echo "==================="
echo "Installing dotfiles"
echo "==================="
echo " "
echo "1. Creating $backupdir to backup any existing dotfiles in ~ ..."
mkdir -p $backupdir
mkdir -p ~/dotfiles_old/config

# Change to the dotfiles directory
cd $dir

for file in $homefiles; do
    echo " "
    echo "[BACKUP] Moving $file from ~ to $backupdir/config ..."
    mv ~/.$file ~/dotfiles_old/
    ln -s $dir/$file ~/.$file
    echo "[LINKED] $file"
done


for file in $configfiles; do
    echo " "
    echo "[BACKUP] Moving $file from ~ to $backupdir/config ..."
    mv ~/.$file ~/dotfiles_old/config
    ln -s $dir/$file ~/.config/$file
    echo "[LINKED] $file"
done


# ===============
# Installers
# ===============

install_vim_plug () {
    # Get the latest version from GitHub
    # Then open vim and :PlugInstall
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo "[INSTALLED] vimplug"
}

install_zplug () {
    # Zplug: manage zsh plugins
    curl -sL get.zplug.sh | zsh
    echo "[INSTALLED] zplug"
}

install_tpm () {
    # tmux Package manager
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    echo "[INSTALLED] tpm (tmux plugin manager)"
}

install_vim_plug
install_zplug
install_tpm
